server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketflow?currentSchema=auth}
    username: ${SPRING_DATASOURCE_USERNAME:ticketflow}
    password: ${SPRING_DATASOURCE_PASSWORD:rafaleo06}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
  flyway:
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change-me-in-a-real-env-file}
  expiration-minutes: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
