server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketflow?currentSchema=booking}
    username: ${SPRING_DATASOURCE_USERNAME:ticketflow}
    password: ${SPRING_DATASOURCE_PASSWORD:rafaleo06}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: booking
  flyway:
    schemas: booking
    default-schema: booking
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

booking:
  reservation-timeout-minutes: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
